services:
    app:
        container_name: ${APP_NAME}-app
        build:
            context: .
            target: php
            args:
                user: ${SYS_USER}
                uid: ${SYS_UID}
                app_port: ${APP_PORT}
        working_dir: /var/www
        volumes:
            - ./:/var/www
            # - ./.docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        restart: unless-stopped
        # command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
        depends_on:
            - mysql
        networks:
            - application

    nginx:
        container_name: ${APP_NAME}-nginx
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./.docker/nginx/dev:/etc/nginx/conf.d
        restart: unless-stopped
        ports:
            - ${APP_PORT}:80
        networks:
            - application
        command: '/bin/sh -c ''nginx -g "daemon off;"'''

    mysql:
        container_name: ${APP_NAME}-mysql
        image: mysql:8.0
        ports:
            - ${FORWARD_DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        restart: unless-stopped
        networks:
            - application

    phpmyadmin:
        container_name: ${APP_NAME}-phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        links:
            - mysql:mysql
        ports:
            - ${PMA_PORT}:80
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: ${DB_HOST}
        depends_on:
            - mysql
        networks:
            - application

    redis:
        container_name: ${APP_NAME}-redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - application

    meilisearch:
        container_name: ${APP_NAME}-meilisearch
        image: getmeili/meilisearch:latest
        restart: unless-stopped
        ports:
            - ${MEILISEARCH_PORT}:7700
        environment:
            # MEILI_NO_ANALYTICS: ${MEILISEARCH_NO_ANALYTICS}
            # MEILI_NO_SENTRY: ${MEILISEARCH_NO_SENTRY}
            MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
        volumes:
            - ./.meilisearch-data:/meilisearch-data
        networks:
            - application

    supervisor:
        container_name: ${APP_NAME}-supervisor
        build:
            context: .
            dockerfile: ./.docker/supervisor/supervisor.dockerfile
            target: supervisor
            args:
                user: ${SYS_USER}
                uid: ${SYS_UID}
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
        restart: unless-stopped
        depends_on:
            - mysql
        networks:
            - application




networks:
  application:
    name: ${APP_NAME}
