services:
    app:
        container_name: ${APP_NAME}-app
        build:
            context: .
            target: php
            args:
                user: ${SYS_USER}
                uid: ${SYS_UID}
                app_port: ${APP_PORT}
                vite_port: ${VITE_PORT}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        restart: unless-stopped
        depends_on:
            - mysql
        networks:
            - application

    nginx:
        container_name: ${APP_NAME}-nginx
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d
        restart: unless-stopped
        ports:
            - ${APP_PORT}:80
        networks:
            - application
        command: '/bin/sh -c ''nginx -g "daemon off;"'''

    mysql:
        container_name: ${APP_NAME}-mysql
        image: mysql:8.0
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        restart: unless-stopped
        networks:
            - application

    phpmyadmin:
        container_name: ${APP_NAME}-phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        links:
            - mysql:mysql
        ports:
            - ${PMA_PORT}:80
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: ${DB_HOST}
        depends_on:
            - mysql
        networks:
            - application

networks:
  application:
    name: ${APP_NAME}