services:
    app:
        container_name: ${APP_NAME}-app
        image: 614575055279.dkr.ecr.us-east-1.amazonaws.com/shaula:latest
        working_dir: /var/www
        restart: unless-stopped
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_NAME=shaula
            - VITE_APP_NAME=${APP_NAME}
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - mysql
        networks:
            - application

    nginx:
        container_name: ${APP_NAME}-nginx
        image: nginx:alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        ports:
            - ${APP_PORT}:80
        networks:
            - application
        depends_on:
            - app

    mysql:
        container_name: ${APP_NAME}-mysql
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped
        networks:
            - application

    redis:
        container_name: ${APP_NAME}-redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - application

    meilisearch:
        container_name: ${APP_NAME}-meilisearch
        image: getmeili/meilisearch:latest
        restart: unless-stopped
        ports:
            - ${MEILISEARCH_PORT}:7700
        environment:
            MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
        volumes:
            - meilisearch_data:/meilisearch-data
        networks:
            - application

volumes:
    mysql_data:
    meilisearch_data:

networks:
    application:
        name: ${APP_NAME}