services:
    app:
        container_name: ${APP_NAME}-app
        image: 614575055279.dkr.ecr.us-east-1.amazonaws.com/shaula:latest
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            # Apenas dados que PRECISAM persistir
            - storage-data:/var/www/storage
            - bootstrap-cache:/var/www/bootstrap/cache
        env_file: .env
        depends_on:
            - mysql
        networks:
            - application

    nginx:
        container_name: ${APP_NAME}-nginx
        image: nginx:alpine
        volumes:
            # Nginx precisa acessar apenas arquivos estáticos
            - app-public:/usr/share/nginx/html:ro
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt:ro
        restart: unless-stopped
        ports:
            - ${APP_PORT}:80
            - "443:443"
        networks:
            - application
        depends_on:
            - app

    # Container init que roda uma vez e para
    assets-init:
        container_name: ${APP_NAME}-assets-init
        image: 614575055279.dkr.ecr.us-east-1.amazonaws.com/shaula:latest
        volumes:
            - app-public:/shared
        command: sh -c "cp -r /var/www/public/* /shared/ && echo 'Assets copiados'"
        restart: "no"

    mysql:
        container_name: ${APP_NAME}-mysql
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/mysql:/docker-entrypoint-initdb.d
            - mysql-data:/var/lib/mysql
        restart: unless-stopped
        networks:
            - application

    redis:
        container_name: ${APP_NAME}-redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - application

    meilisearch:
        container_name: ${APP_NAME}-meilisearch
        image: getmeili/meilisearch:latest
        restart: unless-stopped
        ports:
            - ${MEILISEARCH_PORT}:7700
        environment:
            MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
        volumes:
            - ./.meilisearch-data:/meilisearch-data
        networks:
            - application

volumes:
  storage-data:     # Para uploads e arquivos gerados pela app
  bootstrap-cache:  # Para cache do Laravel
  app-public:       # Para assets estáticos
  mysql-data:

networks:
  application:
    name: ${APP_NAME}