server {
    listen 80;
    listen [::]:80;
    server_name shaula.ufrn.br www.shaula.ufrn.br;

    # Redirect all HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name shaula.ufrn.br www.shaula.ufrn.br;

    ssl_certificate /etc/letsencrypt/live/shaula.ufrn.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shaula.ufrn.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;

    client_max_body_size 500M;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location /storage/ {
        add_header 'Access-Control-Allow-Origin' '*';
    }
}